"""create postcode table

Revision ID: 262400159e34
Revises: 
Create Date: 2025-11-10 15:16:56.751127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262400159e34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Postcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('address3', sa.String(), nullable=True),
    sa.Column('kana1', sa.String(), nullable=True),
    sa.Column('kana2', sa.String(), nullable=True),
    sa.Column('kana3', sa.String(), nullable=True),
    sa.Column('prefcode', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Postcode')
    # ### end Alembic commands ###
