"""recreate postcode table

Revision ID: bd7d733d3d34
Revises: 
Create Date: 2025-11-14 22:57:00.526240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7d733d3d34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Postcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('kana1', sa.String(length=255), nullable=True),
    sa.Column('kana2', sa.String(length=255), nullable=True),
    sa.Column('kana3', sa.String(length=255), nullable=True),
    sa.Column('prefcode', sa.String(length=255), nullable=True),
    sa.Column('zipcode', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Postcode')
    # ### end Alembic commands ###
